// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: studentpb/student.proto

package studentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age           *int32                 `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_studentpb_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_studentpb_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_studentpb_student_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Student) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Student) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_studentpb_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_studentpb_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_studentpb_student_proto_rawDescGZIP(), []int{1}
}

func (x *GetStudentRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type SetStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStudentResponse) Reset() {
	*x = SetStudentResponse{}
	mi := &file_studentpb_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStudentResponse) ProtoMessage() {}

func (x *SetStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_studentpb_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStudentResponse.ProtoReflect.Descriptor instead.
func (*SetStudentResponse) Descriptor() ([]byte, []int) {
	return file_studentpb_student_proto_rawDescGZIP(), []int{2}
}

func (x *SetStudentResponse) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

var File_studentpb_student_proto protoreflect.FileDescriptor

const file_studentpb_student_proto_rawDesc = "" +
	"\n" +
	"\x17studentpb/student.proto\x12\astudent\"?\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"#\n" +
	"\x11GetStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12SetStudentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x8d\x01\n" +
	"\x0eStudentService\x12<\n" +
	"\n" +
	"GetStudent\x12\x1a.student.GetStudentRequest\x1a\x10.student.Student\"\x00\x12=\n" +
	"\n" +
	"SetStudent\x12\x10.student.Student\x1a\x1b.student.SetStudentResponse\"\x00B3Z1github.com/xavicci/gRPC-Student-Service;studentpb"

var (
	file_studentpb_student_proto_rawDescOnce sync.Once
	file_studentpb_student_proto_rawDescData []byte
)

func file_studentpb_student_proto_rawDescGZIP() []byte {
	file_studentpb_student_proto_rawDescOnce.Do(func() {
		file_studentpb_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_studentpb_student_proto_rawDesc), len(file_studentpb_student_proto_rawDesc)))
	})
	return file_studentpb_student_proto_rawDescData
}

var file_studentpb_student_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_studentpb_student_proto_goTypes = []any{
	(*Student)(nil),            // 0: student.Student
	(*GetStudentRequest)(nil),  // 1: student.GetStudentRequest
	(*SetStudentResponse)(nil), // 2: student.SetStudentResponse
}
var file_studentpb_student_proto_depIdxs = []int32{
	1, // 0: student.StudentService.GetStudent:input_type -> student.GetStudentRequest
	0, // 1: student.StudentService.SetStudent:input_type -> student.Student
	0, // 2: student.StudentService.GetStudent:output_type -> student.Student
	2, // 3: student.StudentService.SetStudent:output_type -> student.SetStudentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_studentpb_student_proto_init() }
func file_studentpb_student_proto_init() {
	if File_studentpb_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_studentpb_student_proto_rawDesc), len(file_studentpb_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_studentpb_student_proto_goTypes,
		DependencyIndexes: file_studentpb_student_proto_depIdxs,
		MessageInfos:      file_studentpb_student_proto_msgTypes,
	}.Build()
	File_studentpb_student_proto = out.File
	file_studentpb_student_proto_goTypes = nil
	file_studentpb_student_proto_depIdxs = nil
}
